import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { LandingPageSchema } from '@org/engine-core';
import type { LandingPage } from '@org/engine-core';

// ---------------------------------------------------------------------------
// Eject — writes a standalone landing-page.tsx the developer can own
// ---------------------------------------------------------------------------

export function eject(cwd: string): void {
  const configPath = join(cwd, 'config.json');

  let raw: unknown;
  try {
    raw = JSON.parse(readFileSync(configPath, 'utf-8'));
  } catch {
    console.error('\nError: config.json not found in the current directory.');
    console.error('Run `siteblaze preview` first to create one.\n');
    process.exit(1);
  }

  const result = LandingPageSchema.safeParse(raw);
  if (!result.success) {
    console.error('\nError: config.json is invalid:');
    for (const issue of result.error.issues) {
      console.error(`  ${issue.path.join('.') || 'root'}: ${issue.message}`);
    }
    process.exit(1);
  }

  const outDir = join(cwd, 'landing-page');
  mkdirSync(outDir, { recursive: true });

  writeFileSync(join(outDir, 'landing-page.tsx'), buildComponent(result.data));
  writeFileSync(join(outDir, 'config.json'), JSON.stringify(result.data, null, 2));

  console.log('\n\x1b[32m✓\x1b[0m  Ejected to \x1b[36mlanding-page/\x1b[0m');
  console.log('   landing-page.tsx  — drop into any React + Tailwind project');
  console.log('   config.json       — edit and re-eject any time');
  console.log('\n\x1b[2mThen in your project:\x1b[0m');
  console.log('  import LandingPage from \'./landing-page/landing-page\';\n');
}

function buildComponent(config: LandingPage): string {
  const configJson = JSON.stringify({ metadata: config.metadata, sections: config.sections }, null, 2);
  return [
    '// Generated by siteblaze — edit freely',
    "import { PageRenderer } from '@siteblaze/react';",
    '',
    `const config = ${configJson} as const;`,
    '',
    'export default function LandingPage() {',
    '  return <PageRenderer config={config} />;',
    '}',
    '',
  ].join('\n');
}
